#!/usr/bin/env bash
# Claudio setup: venv + Vosk model in your language + global `claudio` command.
# Usage:
#   bash setup.sh              # interactive (suggests your system language)
#   bash setup.sh en           # pick a language directly
#   bash setup.sh en jarvis    # language + custom wake word
set -eu

DATA="$HOME/.local/share/claudio"
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
mkdir -p "$DATA"

# --- supported languages: Vosk small models (~40-50 MB each) ----------------
declare -A MODELS=(
    [es]=vosk-model-small-es-0.42
    [en]=vosk-model-small-en-us-0.15
    [pt]=vosk-model-small-pt-0.3
    [fr]=vosk-model-small-fr-0.22
    [de]=vosk-model-small-de-0.15
    [it]=vosk-model-small-it-0.22
    [ca]=vosk-model-small-ca-0.4
    [nl]=vosk-model-small-nl-0.22
    [ru]=vosk-model-small-ru-0.22
    [hi]=vosk-model-small-hi-0.22
    [zh]=vosk-model-small-cn-0.22
    [ja]=vosk-model-small-ja-0.22
)
# default wake word per language (any single word the model recognizes works)
declare -A WAKES=(
    [es]=claudio [it]=claudio [pt]=claudio [ca]=claudio
    [en]=claude  [fr]=claude  [de]=claude  [nl]=claude
    [ru]=клод    [hi]=क्लॉड    [zh]=克劳德   [ja]=クロード
)

# --- language selection: detect from system locale, allow override ----------
sys_lang="${LANG%%[._]*}"; sys_lang="${sys_lang%%_*}"
[ -n "${MODELS[$sys_lang]+x}" ] || sys_lang=en

lang="${1:-}"
if [ -z "$lang" ]; then
    echo "Available languages: ${!MODELS[*]}"
    if [ -t 0 ]; then
        read -r -p "Language [$sys_lang]: " lang
    fi
    lang="${lang:-$sys_lang}"
fi
if [ -z "${MODELS[$lang]+x}" ]; then
    echo "Unsupported language: '$lang'. Available: ${!MODELS[*]}" >&2
    exit 1
fi

wake="${2:-}"
if [ -z "$wake" ] && [ -t 0 ]; then
    read -r -p "Wake word (one word) [${WAKES[$lang]}]: " wake
fi
wake="${wake:-${WAKES[$lang]}}"

echo "Language: $lang — wake word: \"$wake\""

# --- venv + vosk ------------------------------------------------------------
if [ ! -x "$DATA/venv/bin/python" ]; then
    echo "Creating venv…"
    python3 -m venv "$DATA/venv"
fi
"$DATA/venv/bin/pip" install --quiet --upgrade vosk

# --- model ------------------------------------------------------------------
model_dir="$DATA/model-$lang"
if [ ! -d "$model_dir" ]; then
    if [ "$lang" = es ] && [ -d "$DATA/model" ]; then
        mv "$DATA/model" "$model_dir"   # migrate pre-multilanguage layout
    else
        name="${MODELS[$lang]}"
        echo "Downloading Vosk model $name…"
        curl -L --progress-bar -o "$DATA/model.zip" "https://alphacephei.com/vosk/models/$name.zip"
        python3 -c "import zipfile; zipfile.ZipFile('$DATA/model.zip').extractall('$DATA')"
        mv "$DATA/$name" "$model_dir"
        rm "$DATA/model.zip"
    fi
fi

# --- config -----------------------------------------------------------------
cat > "$DATA/config" <<EOF
CLAUDIO_LANG=$lang
CLAUDIO_WAKE=$wake
EOF

# --- global `claudio` command -----------------------------------------------
mkdir -p "$HOME/.local/bin"
cat > "$HOME/.local/bin/claudio" <<EOF
#!/usr/bin/env bash
# Claudio — global command (generated by setup.sh).
#   claudio code [dir]   open Claude Code in tmux in a project (default: cwd);
#                        voice commands get typed there
#   claudio start|stop|status|log|fg   control the voice daemon
set -u
REPO="$DIR"
case "\${1:-}" in
    code)
        d="\$(cd "\${2:-\$PWD}" 2>/dev/null && pwd)" || { echo "Invalid directory: \${2:-}"; exit 1; }
        name="claudio-\$(basename "\$d" | tr -c 'A-Za-z0-9_-' '-' | sed 's/-*\$//')"
        exec tmux new-session -A -s "\$name" -c "\$d" claude
        ;;
    start|stop|status|log|fg|tmux)
        exec bash "\$REPO/claudio.sh" "\$1"
        ;;
    *)
        echo "Usage: claudio {code [dir]|start|stop|status|log|fg}"
        exit 1
        ;;
esac
EOF
chmod +x "$HOME/.local/bin/claudio" 2>/dev/null || true

# --- systemd user service (optional autostart) ------------------------------
cat > "$DATA/claudio.service" <<EOF
[Unit]
Description=Claudio - voice assistant for Claude Code
After=default.target sound.target

[Service]
ExecStart=$DATA/venv/bin/python $DIR/claudio.py
Environment=CLAUDIO_WORKDIR=$DIR
Restart=on-failure
RestartSec=10

[Install]
WantedBy=default.target
EOF

echo
echo "Done. Start with:  claudio start   (or: bash claudio.sh start)"
echo "Autostart on login (optional):"
echo "  cp $DATA/claudio.service ~/.config/systemd/user/ && systemctl --user enable --now claudio"
